# Generated by Django 4.2.3 on 2023-07-25 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_accounts_ordermaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='date_of_purchase',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 19, 54, 50, 499678)),
        ),
    ]
